        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar  8 16:09:22 2024
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE ORDERDATA__genmod
          INTERFACE 
            SUBROUTINE ORDERDATA(NUMBEROFVALUES,ORDERARRAY,DEEPSOILCOND1&
     &,SHALLOWSOILCOND1,SHALLOWSOILDEPTH1,AEPERATIO1,URBAN1,NSECAL,     &
     &BIASCAL,KGECAL,LOGNSECAL,RMSECAL,PEACAL,SPECAL,NSEVAL,BIASVAL,    &
     &KGEVAL,LOGNSEVAL,RMSEVAL,PEAVAL,SPEVAL)
              INTEGER(KIND=4), INTENT(IN) :: NUMBEROFVALUES
              REAL(KIND=4), INTENT(INOUT) :: ORDERARRAY(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: DEEPSOILCOND1(             &
     &NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: SHALLOWSOILCOND1(          &
     &NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: SHALLOWSOILDEPTH1(         &
     &NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: AEPERATIO1(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: URBAN1(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: NSECAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: BIASCAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: KGECAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: LOGNSECAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: RMSECAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: PEACAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: SPECAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: NSEVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: BIASVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: KGEVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: LOGNSEVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: RMSEVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: PEAVAL(NUMBEROFVALUES)
              REAL(KIND=4), INTENT(INOUT) :: SPEVAL(NUMBEROFVALUES)
            END SUBROUTINE ORDERDATA
          END INTERFACE 
        END MODULE ORDERDATA__genmod
