        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar  8 16:09:22 2024
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE REDUCEDURBANRAIN__genmod
          INTERFACE 
            SUBROUTINE REDUCEDURBANRAIN(LIBRARYFILE,FILELENGTH,TEXT,    &
     &SOILDETEND,NODISCHARGEVALUES,URBANRAINFRACTION,NROWS,NCOLS,       &
     &VEGTYPENEW)
              INTEGER(KIND=4), INTENT(IN) :: NCOLS
              INTEGER(KIND=4), INTENT(IN) :: NROWS
              INTEGER(KIND=4), INTENT(IN) :: NODISCHARGEVALUES
              INTEGER(KIND=4), INTENT(IN) :: FILELENGTH
              CHARACTER(LEN=300), INTENT(IN) :: LIBRARYFILE
              CHARACTER(LEN=300), INTENT(IN) :: TEXT(FILELENGTH)
              INTEGER(KIND=4), INTENT(IN) :: SOILDETEND
              REAL(KIND=4), INTENT(IN) :: URBANRAINFRACTION
              INTEGER(KIND=4), INTENT(IN) :: VEGTYPENEW(NROWS,NCOLS)
            END SUBROUTINE REDUCEDURBANRAIN
          END INTERFACE 
        END MODULE REDUCEDURBANRAIN__genmod
