        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar  8 16:09:23 2024
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE WRITEXMLFILE__genmod
          INTERFACE 
            SUBROUTINE WRITEXMLFILE(DISCHARGEFILENAME,RUNDATAFILENAME,  &
     &LIBRARYFILE,FILELENGTH,TEXT,SIMNUMBER,VEGEND,SOILPROPEND,         &
     &SOILDETEND,NODISCHARGEVALUES,CALIBRATIONTIMES,VALIDATIONTIMES,NOS,&
     &MEASUREDDISCHARGE,SUBAEPERATIO,SUBSHALLOWSOILCOND,SUBDEEPSOILCOND,&
     &SUBSHALLOWSOILDEPTH,SUBURBAN,SUBBIASCAL,SUBNSECAL,SUBKGECAL,      &
     &SUBLOGNSECAL,RMSECAL,PEARSONCAL,SPEARMANCAL,SUBBIASVAL,SUBNSEVAL, &
     &SUBKGEVAL,SUBLOGNSEVAL,RMSEVAL,PEARSONVAL,SPEARMANVAL,NROWS,NCOLS,&
     &VEGTYPENEW,CALSTART,CALFIN,VALSTART,VALFINISH,GROUNDLEVELFILEPATH,&
     &SIMULATEDLEVELFILEPATH)
              INTEGER(KIND=4), INTENT(IN) :: NCOLS
              INTEGER(KIND=4), INTENT(IN) :: NROWS
              INTEGER(KIND=4), INTENT(IN) :: NODISCHARGEVALUES
              INTEGER(KIND=4), INTENT(IN) :: FILELENGTH
              CHARACTER(LEN=300), INTENT(IN) :: DISCHARGEFILENAME
              CHARACTER(LEN=300), INTENT(IN) :: RUNDATAFILENAME
              CHARACTER(LEN=300), INTENT(IN) :: LIBRARYFILE
              CHARACTER(LEN=300), INTENT(IN) :: TEXT(FILELENGTH)
              INTEGER(KIND=4), INTENT(IN) :: SIMNUMBER
              INTEGER(KIND=4), INTENT(IN) :: VEGEND
              INTEGER(KIND=4), INTENT(IN) :: SOILPROPEND
              INTEGER(KIND=4), INTENT(IN) :: SOILDETEND
              INTEGER(KIND=4), INTENT(IN) :: CALIBRATIONTIMES(2)
              INTEGER(KIND=4), INTENT(IN) :: VALIDATIONTIMES(2)
              INTEGER(KIND=4), INTENT(IN) :: NOS
              REAL(KIND=4), INTENT(IN) :: MEASUREDDISCHARGE(            &
     &NODISCHARGEVALUES)
              REAL(KIND=4), INTENT(IN) :: SUBAEPERATIO
              REAL(KIND=4), INTENT(IN) :: SUBSHALLOWSOILCOND
              REAL(KIND=4), INTENT(IN) :: SUBDEEPSOILCOND
              REAL(KIND=4), INTENT(IN) :: SUBSHALLOWSOILDEPTH
              REAL(KIND=4), INTENT(IN) :: SUBURBAN
              REAL(KIND=4), INTENT(OUT) :: SUBBIASCAL
              REAL(KIND=4), INTENT(OUT) :: SUBNSECAL
              REAL(KIND=4), INTENT(OUT) :: SUBKGECAL
              REAL(KIND=4), INTENT(OUT) :: SUBLOGNSECAL
              REAL(KIND=4), INTENT(OUT) :: RMSECAL
              REAL(KIND=4), INTENT(OUT) :: PEARSONCAL
              REAL(KIND=4), INTENT(OUT) :: SPEARMANCAL
              REAL(KIND=4), INTENT(OUT) :: SUBBIASVAL
              REAL(KIND=4), INTENT(OUT) :: SUBNSEVAL
              REAL(KIND=4), INTENT(OUT) :: SUBKGEVAL
              REAL(KIND=4), INTENT(OUT) :: SUBLOGNSEVAL
              REAL(KIND=4), INTENT(OUT) :: RMSEVAL
              REAL(KIND=4), INTENT(OUT) :: PEARSONVAL
              REAL(KIND=4), INTENT(OUT) :: SPEARMANVAL
              INTEGER(KIND=4), INTENT(IN) :: VEGTYPENEW(NROWS,NCOLS)
              INTEGER(KIND=4), INTENT(IN) :: CALSTART
              INTEGER(KIND=4), INTENT(IN) :: CALFIN
              INTEGER(KIND=4), INTENT(IN) :: VALSTART
              INTEGER(KIND=4), INTENT(IN) :: VALFINISH
              CHARACTER(LEN=300), INTENT(IN) :: GROUNDLEVELFILEPATH
              CHARACTER(LEN=300), INTENT(IN) :: SIMULATEDLEVELFILEPATH
            END SUBROUTINE WRITEXMLFILE
          END INTERFACE 
        END MODULE WRITEXMLFILE__genmod
